### ISSUE TITLE
Old rspec description warning

### ISSUE THREAD

**Issue by huyu398** [gogotanaka/hilbert#29]
rspec が 3.0.0 から `be_false`, `be_true` の記法を廃止するようです．
今後は， `be_falsey` か `be false` のような記法にしたほうが良いとのこと．

`gem update` を行うとこの問題に当たったので， Gemfile, gemspec で使用する rspec の version を指定したほうが良さそうです．

```
Deprecation Warnings:

--------------------------------------------------------------------------------
RSpec::Core::ExampleGroup#example is deprecated and will be removed
in RSpec 3. There are a few options for what you can use instead:

  - rspec-core's DSL methods (`it`, `before`, `after`, `let`, `subject`, etc)
    now yield the example as a block argument, and that is the recommended
    way to access the current example from those contexts.
  - The current example is now exposed via `RSpec.current_example`,
    which is accessible from any context.
  - If you can't update the code at this call site (e.g. because it is in
    an extension gem), you can use this snippet to continue making this
    method available in RSpec 2.99 and RSpec 3:

      RSpec.configure do |c|
        c.expose_current_running_example_as :example
      end

(Called from /home/user/workspace/dydx/spec/lib/delta_spec.rb:13:in `block (2 levels) in <top (required)>')
--------------------------------------------------------------------------------

`be_false` is deprecated. Use `be_falsey` (for Ruby's conditional semantics) or `be false` (for exact `== false` equality) instead. Called from /home/user/workspace/dydx/spec/lib/algebra/formula_spec.rb:61:in `block (3 levels) in <top (required)>'.
`be_false` is deprecated. Use `be_falsey` (for Ruby's conditional semantics) or `be false` (for exact `== false` equality) instead. Called from /home/user/workspace/dydx/spec/lib/algebra/formula_spec.rb:67:in `block (3 levels) in <top (required)>'.
`be_false` is deprecated. Use `be_falsey` (for Ruby's conditional semantics) or `be false` (for exact `== false` equality) instead. Called from /home/user/workspace/dydx/spec/lib/helper_spec.rb:21:in `block (3 levels) in <top (required)>'.
Too many uses of deprecated '`be_false`'. Pass `--deprecation-out` or set `config.deprecation_stream` to a file for full output.

`be_true` is deprecated. Use `be_truthy` (for Ruby's conditional semantics) or `be true` (for exact `== true` equality) instead. Called from /home/user/workspace/dydx/spec/lib/algebra/formula_spec.rb:60:in `block (3 levels) in <top (required)>'.
`be_true` is deprecated. Use `be_truthy` (for Ruby's conditional semantics) or `be true` (for exact `== true` equality) instead. Called from /home/user/workspace/dydx/spec/lib/algebra/formula_spec.rb:65:in `block (3 levels) in <top (required)>'.
`be_true` is deprecated. Use `be_truthy` (for Ruby's conditional semantics) or `be true` (for exact `== true` equality) instead. Called from /home/user/workspace/dydx/spec/lib/algebra/formula_spec.rb:66:in `block (3 levels) in <top (required)>'.
Too many uses of deprecated '`be_true`'. Pass `--deprecation-out` or set `config.deprecation_stream` to a file for full output.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

45 deprecation warnings total
```

**Comment by gogotanaka** [comment]
報告ありがとうございます！

記法を3.0.0に合わせる方向で行きましょう.

僕がやっておきます.

**Comment by gogotanaka** [comment]
https://github.com/gogotanaka/dydx/commit/a407347fec834e2cbb68c74d22503d9d9550bf6f

https://github.com/gogotanaka/dydx/commit/837d731506e5c4f9d099e529cc02dc54d5f8633c
