### ISSUE TITLE
lim[x->oo] (1 + 1/x)^x  example hangs

### ISSUE THREAD

**Issue by bobfoster** [gogotanaka/hilbert#71]
$ hilbert -i
Enjoy! -> postulate zfc_analysis
success! :)
Enjoy! -> lim[x->oo](1 + 1/x)^x
(hangs)
^C/Library/Ruby/Gems/2.0.0/gems/hilbert-0.0.2700300/lib/hilbert/iq.rb:16:in `eval': /Library/Ruby/Gems/2.0.0/gems/dydx-0.2.7000001/lib/dydx/algebra/set.rb:180:in`**':  (Interrupt)
    from /Library/Ruby/Gems/2.0.0/gems/dydx-0.2.7000001/lib/dydx/algebra/set.rb:180:in `block (3 levels) in <module:Set>'
    from /Library/Ruby/Gems/2.0.0/gems/dydx-0.2.7000001/lib/dydx/algebra/operator/parts/num.rb:9:in`block (2 levels) in module:Num'
    from /Library/Ruby/Gems/2.0.0/gems/dydx-0.2.7000001/lib/dydx/algebra/operator/parts/general.rb:95:in `block (2 levels) in <module:General2>'
    from /Library/Ruby/Gems/2.0.0/gems/dydx-0.2.7000001/lib/dydx/algebra/operator/parts/general.rb:83:in`block (2 levels) in module:General1'
    from /Library/Ruby/Gems/2.0.0/gems/dydx-0.2.7000001/lib/dydx/algebra/operator/parts/general.rb:44:in `block (2 levels) in <module:Associative>'
    from /Library/Ruby/Gems/2.0.0/gems/dydx-0.2.7000001/lib/dydx/algebra/operator/parts/general.rb:14:in`block (2 levels) in module:Interface'
    from /Library/Ruby/Gems/2.0.0/gems/dydx-0.2.7000001/lib/dydx/algebra/formula.rb:76:in `subst'
    from /Library/Ruby/Gems/2.0.0/gems/dydx-0.2.7000001/lib/dydx/function.rb:16:in`evalue'
    from /Library/Ruby/Gems/2.0.0/gems/dydx-0.2.7000001/lib/dydx.rb:22:in `block (2 levels) in <module:Dydx>'
    from (eval):2:in`execute'
    from /Library/Ruby/Gems/2.0.0/gems/hilbert-0.0.2700300/lib/hilbert/iq.rb:16:in `eval'
    from /Library/Ruby/Gems/2.0.0/gems/hilbert-0.0.2700300/lib/hilbert/iq.rb:16:in`execute'
    from /Library/Ruby/Gems/2.0.0/gems/hilbert-0.0.2700300/bin/hilbert:25:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/hilbert-0.0.2700300/bin/hilbert:21:in`loop'
    from /Library/Ruby/Gems/2.0.0/gems/hilbert-0.0.2700300/bin/hilbert:21:in `<top (required)>'
    from /usr/bin/hilbert:23:in`load'
    from /usr/bin/hilbert:23:in `<main>'

**Comment by gogotanaka** [comment]
@bobfoster thank for reporting! I've confirmed what you mentioned is right on Ruby2.0.0.
(Actually it doesn't happen  on Ruby2.1.0>)

I'm gonna fix it. Please give me some time.
